name: Build ToughRADIUS

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'   # 根据 ToughRADIUS 的 go.mod 要求修改

      - name: Verify Go version
        run: go version

      - name: Get dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

      - name: Build binary
        run: |
          mkdir -p build
          go build -o build/toughradius ./cmd/toughradius
          ls -lh build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: toughradius-binary
          path: build/*
